export const SERVER_SET_PATH = 'SERVER_SET_PATH';
export const SERVER_START = 'SERVER_START';
export const SERVER_STOP = 'SERVER_STOP';
export const SERVER_UNLOAD_DB = 'SERVER_UNLOAD_DB';
export const INDEXER_STARTED = 'INDEXER_STARTED';
export const INDEXER_FINISHED = 'INDEXER_FINISHED';
