export default {
	PLAYER_PAUSE: 'PLAYER_PAUSE',
	PLAYER_PLAY: 'PLAYER_PLAY',
	PLAYER_PREV: 'PLAYER_PREV',
	PLAYER_NEXT: 'PLAYER_NEXT',

	QUEUE_GOTO: 'QUEUE_GOTO',

	ZONE_GROUP_SELECT: 'ZONE_GROUP_SELECT',
	ZONE_GROUP_SET: 'ZONE_GROUP_SET',

	SONOS_SERVICE_ZONES_UPDATE: 'SONOS_SERVICE_ZONEGROUPS_UPDATE',
	SONOS_SERVICE_ZONEGROUPS_DEFAULT: 'SONOS_SERVICE_ZONEGROUPS_DEFAULT',
	SONOS_SERVICE_QUEUE_UPDATE: 'SONOS_SERVICE_QUEUE_UPDATE',
	SONOS_SERVICE_VOLUME_UPDATE: 'SONOS_SERVICE_VOLUME_UPDATE',
	SONOS_SERVICE_PLAYSTATE_UPDATE: 'SONOS_SERVICE_PLAYSTATE_UPDATE',
	SONOS_SERVICE_CURRENT_TRACK_UPDATE: 'SONOS_SERVICE_CURRENT_TRACK_UPDATE',
	SONOS_SERVICE_POSITION_INFO_UPDATE: 'SONOS_SERVICE_POSITION_INFO_UPDATE',
};