name: sonos-controller-unofficial # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.3.0-alpha4' # just for humans, typically '1.2+git' or '1.3.2'
summary: Unofficial Sonos Controller for Linux # 79 char long summary
description: |
  An Electron based app to control Sonos systems on Linux desktops.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
